name: core_security
description: Root/jailbreak detection and app lifecycle security. Locks vault on background.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  safe_device: ^1.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
